package com.mybatis.datediff.model;

public class DateDiff {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reactspring.date_diff.pk
	 * @mbg.generated  Mon Apr 17 19:48:41 CDT 2023
	 */
	private Integer pk;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reactspring.date_diff.years
	 * @mbg.generated  Mon Apr 17 19:48:41 CDT 2023
	 */
	private Long years;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reactspring.date_diff.months
	 * @mbg.generated  Mon Apr 17 19:48:41 CDT 2023
	 */
	private Long months;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reactspring.date_diff.weeks
	 * @mbg.generated  Mon Apr 17 19:48:41 CDT 2023
	 */
	private Long weeks;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reactspring.date_diff.days
	 * @mbg.generated  Mon Apr 17 19:48:41 CDT 2023
	 */
	private Long days;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reactspring.date_diff.hours
	 * @mbg.generated  Mon Apr 17 19:48:41 CDT 2023
	 */
	private Long hours;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reactspring.date_diff.minutes
	 * @mbg.generated  Mon Apr 17 19:48:41 CDT 2023
	 */
	private Long minutes;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reactspring.date_diff.seconds
	 * @mbg.generated  Mon Apr 17 19:48:41 CDT 2023
	 */
	private Long seconds;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reactspring.date_diff.from_date
	 * @mbg.generated  Mon Apr 17 19:48:41 CDT 2023
	 */
	private String fromDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reactspring.date_diff.from_time
	 * @mbg.generated  Mon Apr 17 19:48:41 CDT 2023
	 */
	private String fromTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reactspring.date_diff.to_date
	 * @mbg.generated  Mon Apr 17 19:48:41 CDT 2023
	 */
	private String toDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reactspring.date_diff.to_time
	 * @mbg.generated  Mon Apr 17 19:48:41 CDT 2023
	 */
	private String toTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reactspring.date_diff.pk
	 * @return  the value of reactspring.date_diff.pk
	 * @mbg.generated  Mon Apr 17 19:48:41 CDT 2023
	 */
	public Integer getPk() {
		return pk;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reactspring.date_diff.pk
	 * @param pk  the value for reactspring.date_diff.pk
	 * @mbg.generated  Mon Apr 17 19:48:41 CDT 2023
	 */
	public void setPk(Integer pk) {
		this.pk = pk;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reactspring.date_diff.years
	 * @return  the value of reactspring.date_diff.years
	 * @mbg.generated  Mon Apr 17 19:48:41 CDT 2023
	 */
	public Long getYears() {
		return years;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reactspring.date_diff.years
	 * @param years  the value for reactspring.date_diff.years
	 * @mbg.generated  Mon Apr 17 19:48:41 CDT 2023
	 */
	public void setYears(Long years) {
		this.years = years;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reactspring.date_diff.months
	 * @return  the value of reactspring.date_diff.months
	 * @mbg.generated  Mon Apr 17 19:48:41 CDT 2023
	 */
	public Long getMonths() {
		return months;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reactspring.date_diff.months
	 * @param months  the value for reactspring.date_diff.months
	 * @mbg.generated  Mon Apr 17 19:48:41 CDT 2023
	 */
	public void setMonths(Long months) {
		this.months = months;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reactspring.date_diff.weeks
	 * @return  the value of reactspring.date_diff.weeks
	 * @mbg.generated  Mon Apr 17 19:48:41 CDT 2023
	 */
	public Long getWeeks() {
		return weeks;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reactspring.date_diff.weeks
	 * @param weeks  the value for reactspring.date_diff.weeks
	 * @mbg.generated  Mon Apr 17 19:48:41 CDT 2023
	 */
	public void setWeeks(Long weeks) {
		this.weeks = weeks;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reactspring.date_diff.days
	 * @return  the value of reactspring.date_diff.days
	 * @mbg.generated  Mon Apr 17 19:48:41 CDT 2023
	 */
	public Long getDays() {
		return days;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reactspring.date_diff.days
	 * @param days  the value for reactspring.date_diff.days
	 * @mbg.generated  Mon Apr 17 19:48:41 CDT 2023
	 */
	public void setDays(Long days) {
		this.days = days;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reactspring.date_diff.hours
	 * @return  the value of reactspring.date_diff.hours
	 * @mbg.generated  Mon Apr 17 19:48:41 CDT 2023
	 */
	public Long getHours() {
		return hours;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reactspring.date_diff.hours
	 * @param hours  the value for reactspring.date_diff.hours
	 * @mbg.generated  Mon Apr 17 19:48:41 CDT 2023
	 */
	public void setHours(Long hours) {
		this.hours = hours;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reactspring.date_diff.minutes
	 * @return  the value of reactspring.date_diff.minutes
	 * @mbg.generated  Mon Apr 17 19:48:41 CDT 2023
	 */
	public Long getMinutes() {
		return minutes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reactspring.date_diff.minutes
	 * @param minutes  the value for reactspring.date_diff.minutes
	 * @mbg.generated  Mon Apr 17 19:48:41 CDT 2023
	 */
	public void setMinutes(Long minutes) {
		this.minutes = minutes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reactspring.date_diff.seconds
	 * @return  the value of reactspring.date_diff.seconds
	 * @mbg.generated  Mon Apr 17 19:48:41 CDT 2023
	 */
	public Long getSeconds() {
		return seconds;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reactspring.date_diff.seconds
	 * @param seconds  the value for reactspring.date_diff.seconds
	 * @mbg.generated  Mon Apr 17 19:48:41 CDT 2023
	 */
	public void setSeconds(Long seconds) {
		this.seconds = seconds;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reactspring.date_diff.from_date
	 * @return  the value of reactspring.date_diff.from_date
	 * @mbg.generated  Mon Apr 17 19:48:41 CDT 2023
	 */
	public String getFromDate() {
		return fromDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reactspring.date_diff.from_date
	 * @param fromDate  the value for reactspring.date_diff.from_date
	 * @mbg.generated  Mon Apr 17 19:48:41 CDT 2023
	 */
	public void setFromDate(String fromDate) {
		this.fromDate = fromDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reactspring.date_diff.from_time
	 * @return  the value of reactspring.date_diff.from_time
	 * @mbg.generated  Mon Apr 17 19:48:41 CDT 2023
	 */
	public String getFromTime() {
		return fromTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reactspring.date_diff.from_time
	 * @param fromTime  the value for reactspring.date_diff.from_time
	 * @mbg.generated  Mon Apr 17 19:48:41 CDT 2023
	 */
	public void setFromTime(String fromTime) {
		this.fromTime = fromTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reactspring.date_diff.to_date
	 * @return  the value of reactspring.date_diff.to_date
	 * @mbg.generated  Mon Apr 17 19:48:41 CDT 2023
	 */
	public String getToDate() {
		return toDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reactspring.date_diff.to_date
	 * @param toDate  the value for reactspring.date_diff.to_date
	 * @mbg.generated  Mon Apr 17 19:48:41 CDT 2023
	 */
	public void setToDate(String toDate) {
		this.toDate = toDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reactspring.date_diff.to_time
	 * @return  the value of reactspring.date_diff.to_time
	 * @mbg.generated  Mon Apr 17 19:48:41 CDT 2023
	 */
	public String getToTime() {
		return toTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reactspring.date_diff.to_time
	 * @param toTime  the value for reactspring.date_diff.to_time
	 * @mbg.generated  Mon Apr 17 19:48:41 CDT 2023
	 */
	public void setToTime(String toTime) {
		this.toTime = toTime;
	}
}