package com.mybatis.datediff.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.mybatis.datediff.model.DateDiff;
import com.mybatis.datediff.model.DateDiffExample;

public interface DateDiffMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reactspring.date_diff
	 * @mbg.generated  Mon Apr 17 19:48:41 CDT 2023
	 */
	long countByExample(DateDiffExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reactspring.date_diff
	 * @mbg.generated  Mon Apr 17 19:48:41 CDT 2023
	 */
	int deleteByExample(DateDiffExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reactspring.date_diff
	 * @mbg.generated  Mon Apr 17 19:48:41 CDT 2023
	 */
	int deleteByPrimaryKey(Integer pk);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reactspring.date_diff
	 * @mbg.generated  Mon Apr 17 19:48:41 CDT 2023
	 */
	int insert(DateDiff row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reactspring.date_diff
	 * @mbg.generated  Mon Apr 17 19:48:41 CDT 2023
	 */
	int insertSelective(DateDiff row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reactspring.date_diff
	 * @mbg.generated  Mon Apr 17 19:48:41 CDT 2023
	 */
	List<DateDiff> selectByExample(DateDiffExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reactspring.date_diff
	 * @mbg.generated  Mon Apr 17 19:48:41 CDT 2023
	 */
	DateDiff selectByPrimaryKey(Integer pk);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reactspring.date_diff
	 * @mbg.generated  Mon Apr 17 19:48:41 CDT 2023
	 */
	int updateByExampleSelective(@Param("row") DateDiff row, @Param("example") DateDiffExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reactspring.date_diff
	 * @mbg.generated  Mon Apr 17 19:48:41 CDT 2023
	 */
	int updateByExample(@Param("row") DateDiff row, @Param("example") DateDiffExample example);
}