package com.mybatis.datediff.mapper;

import com.mybatis.datediff.model.DateDiff;
import com.mybatis.datediff.model.DateDiffExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DateDiffMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reactspring.date_diff
     *
     * @mbg.generated
     */
    long countByExample(DateDiffExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reactspring.date_diff
     *
     * @mbg.generated
     */
    int deleteByExample(DateDiffExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reactspring.date_diff
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer pk);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reactspring.date_diff
     *
     * @mbg.generated
     */
    int insert(DateDiff row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reactspring.date_diff
     *
     * @mbg.generated
     */
    int insertSelective(DateDiff row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reactspring.date_diff
     *
     * @mbg.generated
     */
    List<DateDiff> selectByExample(DateDiffExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reactspring.date_diff
     *
     * @mbg.generated
     */
    DateDiff selectByPrimaryKey(Integer pk);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reactspring.date_diff
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") DateDiff row, @Param("example") DateDiffExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reactspring.date_diff
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") DateDiff row, @Param("example") DateDiffExample example);
}